AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  patientcheckout

  Sample SAM Template for patientcheckout

Globals:
  Function:
    Runtime: java11
    MemorySize: 512
    Timeout: 20

Resources:
  PatientCheckoutDLQ:
    Type: AWS::SNS::Topic
  PatientCheckoutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
  PatientCheckoutTopic:
    Type: AWS::SNS::Topic
  PatientCheckoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      # MaximumRetryAttempts: 0
      CodeUri: patientcheckout
      Handler: com.aws.lambda.s3sns.PatientCheckoutLambda::handler
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref PatientCheckoutDLQ
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt PatientCheckoutTopic.TopicName
      Environment:
        Variables:
          PATIENT_CHECKOUT_TOPIC: !Ref PatientCheckoutTopic
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref PatientCheckoutBucket
            Events: s3:ObjectCreated:*
  BillManagementFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: patientcheckout
      Handler: com.aws.lambda.s3sns.BillManagementLambda::handler
      Events:
        SNSEvent:
          Type: SNS 
          Properties:
            Topic: !Ref PatientCheckoutTopic
  ErrorHandlingFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: patientcheckout
      Handler: com.aws.lambda.s3sns.errorhandling.ErrorHandler::handler
      Events:
        SNSEvent:
          Type: SNS 
          Properties:
            Topic: !Ref PatientCheckoutDLQ